FROM {{ @('services.console.build.from') }}

COPY .my127ws/docker/image/console/root /
RUN useradd build \
 && apt-get update && apt-get install -y rsync \
 && ([ -e /sbin/tini ] || curl --fail --silent --show-error --location --output /sbin/tini https://github.com/krallin/tini/releases/download/v0.19.0/tini) \
 && chmod +x /sbin/tini

ENV APP_MODE={{ @('app.mode') }} \
  APP_BUILD={{ @('app.build') }} \
  ASSETS_DIR={{ @('assets.local') }}
{%- set extra_environment_variables=@('services.console.build.environment')|filter(v => v is not empty) %}
{%- if extra_environment_variables %}
{%- for name, value in extra_environment_variables %} \
  {{ name }}="{{ value }}"
{%- endfor %}
{% endif %}

USER build

{% if @('app.build') == 'static' %}
COPY --chown=build:build .my127ws/application  /home/build/application
COPY --chown=build:build ./                    /app
RUN app build
{% else %}
VOLUME /app
VOLUME /home/build/application
{% endif %}

USER root

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sleep", "infinity"]
