{{- with .Values.persistence.postgres -}}
{{- if and .enabled ($.Values.services | dig "postgres" "enabled" false) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-postgres-pv-claim
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: postgres
    app.service: {{ $.Release.Name }}-postgres
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
{{- if .selector }}
  selector:
  {{- .selector | toYaml | nindent 4 }}
{{- end }}

{{- end }}

{{- end }}
