{{ if .Values.services.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: postgres
    app.service: {{ .Release.Name }}-postgres
  name: {{ .Release.Name }}-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.service: {{ .Release.Name }}-postgres
status:
  loadBalancer: {}
{{ end }}
