{{- if .Values.docker.image_pull_config }}
{{- if .Values.global.sealed_secrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{ else }}
apiVersion: v1
kind: Secret
{{ end }}
metadata:
  name: {{ .Release.Name }}-image-pull-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- if .root.Values.global.sealed_secrets.enabled }}
    sealedsecrets.bitnami.com/{{ .root.Values.global.sealed_secrets.scope }}: "true"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      labels:
        {{- include "chart.labels" $ | nindent 8 }}
  encryptedData:
    .dockerconfigjson: {{ .Values.docker.image_pull_config }}
{{- else }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.docker.image_pull_config }}
{{- end }}
{{- end }}
