{{- if .Values.services | dig "solr" "enabled" false }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: solr
    app.service: {{ .Release.Name }}-solr
  name: {{ .Release.Name }}-solr-headless
spec:
  clusterIP: None
  ports:
  - name: solr
    port: 8983
    targetPort: 8983
  selector:
    app.service: {{ .Release.Name }}-solr
{{- end }}
