{{- with .Values.services.solr -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-solr
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: solr
    app.service: {{ $.Release.Name }}-solr
spec:
  {{- with (pick . "replicas" "revisionHistoryLimit") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.service: {{ $.Release.Name }}-solr
  serviceName: {{ $.Release.Name }}-solr-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: solr
        app.service: {{ $.Release.Name }}-solr
    spec:
      {{- with (pick . "affinity") }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      securityContext:
        fsGroup: 8983
        runAsUser: 8983
      containers:
      - name: solr
        env:
        {{- range $key, $value := .environment }}
        {{- $tp := typeOf $value }}
        - name: {{ $key | quote }}
        {{- if eq $tp "string" }}
          value: {{ tpl $value $ | quote }}
        {{- else}}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        ports:
        - name: solr
          containerPort: 8983
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            {{- with (.resources | dig "cpu" "request" nil) }}
            cpu: {{ . }}
            {{- end }}
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 8983
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: {{ $.Release.Name }}-solr-data
          mountPath: {{ .environment.SOLR_VOLUME_DIR | quote }}
      {{- if $.Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ $.Release.Name }}-image-pull-config
      {{- end }}
      enableServiceLinks: false
      restartPolicy: Always
      volumes:
      - name: {{ $.Release.Name }}-solr-data
        emptyDir: {}
      topologySpreadConstraints: {{- (include "pod.topologySpreadConstraints" (dict "root" $ "serviceName" "solr" "service" .)) | nindent 8 }}
{{- with $.Values.persistence.solr -}}
{{- if .enabled }}
  volumeClaimTemplates:
    - {{ include "statefulset.volumeClaimTemplate" (dict "root" $ "name" "solr-data" "serviceName" "solr") | nindent 8 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
