{{ if .Values.services.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: varnish
    app.service: {{ .Release.Name }}-varnish
  name: {{ .Release.Name }}-varnish-headless
spec:
  clusterIP: None
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Release.Name }}-varnish
status:
  loadBalancer: {}
{{ end }}
