{{- with .Values.services.mysql -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mysql
    app.service: {{ $.Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ $.Release.Name }}-mysql
{{- if $.Values.persistence.mysql.enabled }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: mysql
        app.service: {{ $.Release.Name }}-mysql
    spec:
      containers:
      - env:
        {{- range $key, $value := (mergeOverwrite (dict) .environment .environment_dynamic) }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Release.Name }}-mysql
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        name: mysql
        {{- if .options }}
        args:
        {{- range $var, $value := .options }}
        {{- if $value }}
        - {{ print "--" $var "=" $value | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: mysql-data
{{- if $.Values.persistence.mysql.enabled }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-mysql-pv-claim
{{- else }}
        emptyDir: {}
{{- end }}
status: {}
{{- end }}
{{- end }}
