{{- range $configName, $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print $.Release.Name "-" $configName | quote }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    {{- if $config.labels }}
    {{- $config.labels | toYaml | nindent 4 }}
    {{- end }}
{{ tpl (pick $config "data") $ | toYaml }}
{{- end }}
