{{- range $serviceName := (.Values.services | keys) -}}
{{- $service := include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml -}}
{{- with $service }}
{{- if and (not (hasPrefix "." $serviceName)) .enabled .autoscaling .autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ print $.Release.Name "-" $serviceName }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
    app.service: {{ print $.Release.Name "-" $serviceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  {{- with (omit .autoscaling "enabled") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ print $.Release.Name "-" $serviceName }}
{{- end }}
{{- end }}
{{- end }}
