{{- range $serviceName := (.Values.services | keys) -}}
{{- $service := include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml -}}
{{- with $service }}
{{- $autoscaling := .autoscaling | default (dict) -}}
{{- if and (not (hasPrefix "_" $serviceName)) .enabled $autoscaling.enabled }}
---
{{- if semverCompare ">=1.23-0" $.Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ print $.Release.Name "-" $serviceName }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
    app.service: {{ print $.Release.Name "-" $serviceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  {{- with (pick $autoscaling "behavior" "minReplicas" "maxReplicas") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  metrics:
    {{- with $autoscaling.metrics }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- with $autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with $autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ print $.Release.Name "-" $serviceName }}
{{- end }}
{{- end }}
{{- end }}
