{{- range $serviceName := (.Values.services | keys) -}}
{{- $service := include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml -}}
{{- if and (not (hasPrefix "_" $serviceName)) $service.jobs -}}
{{- range $jobName, $jobConfig := $service.jobs }}
{{- with (mergeOverwrite (deepCopy $service) (deepCopy $jobConfig))}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ print $.Release.Name "-" $jobName }}
  {{- $jobMeta := pick $jobConfig "annotations" -}}
  {{- if $jobMeta }}
  {{- toYaml $jobMeta | nindent 2 }}
  {{- end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $jobConfig.component | default $jobName }}
spec:
  {{- $jobSpec := pick $jobConfig "activeDeadlineSeconds" "backoffLimit" "ttlSecondsAfterFinished" }}
  {{- if $jobSpec }}
  {{- $jobSpec | toYaml | nindent 2 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $jobConfig.component | default $jobName }}
    spec:
      {{- $podSpec := pick $service "affinity" "hostAliases" "securityContext" }}
      {{- if $podSpec }}
      {{- $podSpec | toYaml | nindent 6 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: app
          {{- include "service.environment" (dict "root" $ "serviceName" $serviceName "service" $service) | nindent 10 }}
          image: {{ .image | quote }}
          imagePullPolicy: Always
          {{- with (pick $jobConfig "command" "args") }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          resources:
            limits:
              memory: {{ .resources.memory }}
            requests:
              memory: {{ .resources.memory }}
          {{- with .volumes }}
          volumeMounts:
            {{- range . }}
            - {{ tpl (toYaml (pick . "name" "mountPath" "readOnly")) $ | nindent 16 }}
            {{- end }}
          {{- end }}
      enableServiceLinks: false
{{- if $.Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ $.Release.Name }}-image-pull-config
{{- end }}
      restartPolicy: Never
      {{- if $service.serviceAccountName }}
      serviceAccountName: {{ tpl $service.serviceAccountName $ | quote }}
      {{- end }}
      topologySpreadConstraints: {{- (include "pod.topologySpreadConstraints" (dict "root" $ "serviceName" $jobName "service" .)) | nindent 12 }}
      {{- with .volumes }}
      volumes:
        {{- range . }}
        - {{ tpl (toYaml (omit . "mountPath" "readOnly")) $ | nindent 12 }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
