{{- range $serviceName := (.Values.services | keys) -}}
{{- $service := include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml -}}
{{- with $service }}
{{- if and (not (hasPrefix "_" $serviceName)) .enabled }}
{{- $autoscaling := .autoscaling | default (dict "minReplicas" 0) -}}
{{- if or (gt (.replicas | default 1 | int) 1) (and $autoscaling.enabled (gt ($autoscaling.minReplicas | int) 1)) }}
---
{{- if semverCompare ">=1.21-0" $.Capabilities.KubeVersion.Version }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ print $.Release.Name "-" $serviceName | quote }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName | quote }}
    app.service: {{ print $.Release.Name "-" $serviceName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  minAvailable: {{ .minAvailable | default 1 | int }}
  selector:
    matchLabels:
      app.service: {{ print $.Release.Name "-" $serviceName | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
