{{- range $serviceName := (.Values.services | keys) -}}
{{- with (include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml) }}
{{- if and (not (hasPrefix "_" $serviceName)) $.Values.global.prometheus.podMonitoring .enabled .metricsEnabled }}
{{- $endpointServices := kindIs "slice" .containers  | ternary (list) (list .) }}
{{- range .containers }}
{{- $endpointServices = append $endpointServices (include "service.resolved" (dict "root" $ "service_name" .) | fromYaml)}}
{{- end }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ print $.Release.Name "-" $serviceName | quote }}
  labels:
    app.service: {{ print $.Release.Name "-" $serviceName | quote }}
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName | quote }}
spec:
  selector:
    matchLabels:
      app.service: {{ print $.Release.Name "-" $serviceName | quote }}
  podMetricsEndpoints:
  {{- range $endpointServices }}
  {{- if and (. | dig "enabled" true) .metricsEndpoints }}
    {{- .metricsEndpoints | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
