{{- range $secretName, $config := .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ print $.Release.Name "-" $secretName | quote }}
  annotations:
    sealedsecrets.bitnami.com/scope: {{ $.Values.global.sealed_secrets.scope }}
{{ if ne $.Values.global.sealed_secrets.scope "strict" }}
    sealedsecrets.bitnami.com/{{ $.Values.global.sealed_secrets.scope }}: "true"
{{ end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    {{- if $config.labels }}
    {{- $config.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
{{ pick $config "encryptedData" | toYaml | indent 2 }}
  template:
    {{- $secretConfig := pick $config "type" }}
    {{- if $secretConfig }}
    {{- $secretConfig | toYaml | nindent 4 }}
    {{- end }}
    metadata:
      labels:
        {{- include "chart.labels" $ | nindent 8 }}
        {{- if $config.labels }}
        {{- $config.labels | toYaml | nindent 8 }}
        {{- end }}
{{- with (pick ($config.template | default (dict)) "data") }}
    {{- . | toYaml | nindent 4 }}
{{- end }}
{{- end }}
