{{- range $serviceName := ($.Values.services | keys) -}}
{{- with (include "service.resolved" (dict "root" $ "service_name" $serviceName) | fromYaml) }}
{{ if not (hasPrefix "_" $serviceName) -}}
---
{{ template "service.environment.secret" (dict "service_name" $serviceName "service" . "root" $) }}
{{- end }}
{{- end }}
{{- end }}
