
attributes:
  namespace: =@('workspace.name') ~ '-' ~ exec("git rev-parse --short HEAD")
  hostname: =@('workspace.name') ~ '.' ~ @('domain')
  app:
    build: static
    version: =exec("git log -n 1 --pretty=format:'%H'")
    mode: production
