pipeline {
    agent {
        docker {
            label 'my127ws'
            alwaysPull true
            image 'quay.io/inviqa_images/workspace:latest'
            args '--entrypoint "" --volume /var/run/docker.sock:/var/run/docker.sock --volume "$HOME/.my127:/root/.my127"'
        }
    }
    environment {
        COMPOSE_DOCKER_CLI_BUILD = 1
        DOCKER_BUILDKIT = 1
        MY127WS_KEY = credentials('base-my127ws-key-20190523')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '30'))
    }
    triggers { cron(env.BRANCH_NAME ==~ /^(master|main|\d+\.\d+\.x)$/ ? 'H H(0-6) * * *' : '') }
    stages {
        stage('Quality Checks') {
            steps {
                sh '.ci/quality'
                milestone(10)
            }
        }
        stage('Tests') {
            matrix {
                axes {
                    axis {
                        name 'MODE'
                        values 'static', 'dynamic', 'dynamic mutagen'
                    }
                }
                stages {
                    stage('Quality') {
                        environment {
                            TEARDOWN_ENVIRONMENT = "no"
                            TEST_MODE = "quality"
                        }
                        steps { sh '.ci/test $MODE' }
                    }
                    stage('Acceptance') {
                        environment {
                            REUSE_EXISTING_WORKSPACE = "yes"
                            TEST_MODE = "acceptance"
                        }
                        steps { sh '.ci/test $MODE' }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
