{{ if and .Values.persistence.redis.enabled .Values.services.redis.enabled -}}

{{- with .Values.persistence.redis -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-redis-pv-claim
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: redis
    app.service: {{ $.Release.Name }}-redis
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
{{- if .selector }}
  selector:
  {{- .selector | toYaml | nindent 4 }}
{{- end }}

{{- end }}

{{- end }}
