{{- if .Values.services | dig "redis" "enabled" false }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: redis
    app.service: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.service: {{ .Release.Name }}-redis
status:
  loadBalancer: {}
{{- end }}
