command('app build'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
  exec: |
    #!bash(workspace:/)|@
    ws external-images pull

    passthru $COMPOSE_BIN build

command('app build <service>'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    SERVICE:    = input.argument('service')
  exec: |
    #!bash(workspace:/)|@
    passthru $COMPOSE_BIN build "${SERVICE}"
