command('app build'):
  exec: |
    #!bash(workspace:/)|@
    ws external-images pull

    passthru docker-compose build

command('app build <service>'):
  env:
    SERVICE: = input.argument('service')
  exec: |
    #!bash(workspace:/)|@
    passthru docker-compose build "${SERVICE}"