function('built_images', [compose_bin]): |
  #!php
  $configRaw = shell_exec($compose_bin . ' config');
  if ($configRaw === null) {
    exit(1);
  }
  $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

  $builtImages = [];

  foreach ($config['services'] as $serviceName => $service) {
    if ($service['image'] && $service['build']) {
      $builtImages[] = $service['image'];
    }
  }
  $allImages = explode("\n", shell_exec('docker image ls -a --format \'{{ print .Repository ":" .Tag }}\''));

  # workspace commands don't allow non-string types
  = join("\n", array_intersect($builtImages, $allImages));

command('built-images ls'):
  env:
    IMAGES: = built_images(@('docker.compose.bin'))
  exec: |
    #!bash
    echo "$IMAGES"

command('cleanup built-images'):
  env:
    BUILD_LABEL: = @('namespace') ~ ':' ~ @('app.version')
  exec: |
    #!bash
    IMAGES=($(ws built-images ls))
    if [ "${#IMAGES[@]}" -gt 0 ]; then
      run docker image rm --force -- "${IMAGES[@]}"
    fi
    run docker image prune --force --filter=label=build="$BUILD_LABEL"
    [ -z "$(docker builder 2>&1)" ] || run docker builder prune --force --filter=label=build="$BUILD_LABEL"
