# this file is not considered part of the public API so changes aren't considered breaking
confd('harness:/'):
  # base templates
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/entrypoint.sh }
  - { src: docker/image/console/root/home/build/.my.cnf }
  - { src: docker/image/console/root/lib/task/database/import.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/lib/task/migrate.sh }
  - { src: docker/image/console/root/lib/task/rabbitmq/vhosts.sh }
  - { src: docker/image/console/root/lib/task/welcome.sh }
  - { src: docker/image/lighthouse/Dockerfile }
  - { src: docker/image/lighthouse/root/app/run.sh }
  - { src: docker/image/solr/Dockerfile }
  - { src: docker/image/tls-offload/root/etc/ssl/certs/app.crt }
  - { src: docker/image/tls-offload/root/etc/ssl/private/app.key }
  - { src: docker/image/varnish/root/etc/varnish/default.vcl }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: mutagen.yml, dst: workspace:/mutagen.yml } # docker-compose.yml render reads this file
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: harness/scripts/enable.sh }
  - { src: helm/app/_twig/templates/service/varnish/configmap.yaml, dst: harness:/helm/app/templates/service/varnish/configmap.yaml }
  - { src: helm/app/values.yaml }
  - { src: helm/app/values-production.yaml }
  - { src: helm/app/values-preview.yaml }
  - { src: helm/app/Chart.yaml }
