
after('harness.install'): |
  #!bash
  ws enable

after('harness.refresh'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    COMPOSE_PROJECT: = @('namespace')
    PULL: = @('docker.pull')
  exec: |
    #!bash(workspace:/)|@
    run $COMPOSE_BIN stop
    run $COMPOSE_BIN up -d --build --pull="${PULL}"
