{{- with .Values.services.rabbitmq -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app.service: {{ $.Release.Name }}-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ $.Release.Name }}-rabbitmq
{{- if $.Values.persistence.rabbitmq.enabled }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
        app.service: {{ $.Release.Name }}-rabbitmq
    spec:
      containers:
      - env:
        {{- range $key, $value := (mergeOverwrite (dict) .environment .environment_dynamic) }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Release.Name }}-rabbitmq
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      restartPolicy: Always
      volumes:
      - name: rabbitmq-data
{{- if $.Values.persistence.rabbitmq.enabled }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-rabbitmq-pv-claim
{{- else }}
        emptyDir: {}
{{- end }}
status: {}
{{- end }}
{{- end }}
