{{- with .Values.services.rabbitmq -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app.service: {{ $.Release.Name }}-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ $.Release.Name }}-rabbitmq
{{- if $.Values.persistence.rabbitmq.enabled }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
        app.service: {{ $.Release.Name }}-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        {{- include "service.environment" (dict "root" $ "serviceName" "rabbitmq" "service" .) | nindent 8 }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            {{- with (.resources | dig "cpu" "request" nil) }}
            cpu: {{ . }}
            {{- end }}
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      restartPolicy: Always
      volumes:
      - name: rabbitmq-data
{{- if $.Values.persistence.rabbitmq.enabled }}
        persistentVolumeClaim:
          claimName: {{ tpl ($.Values.persistence.rabbitmq.claimName | default "") $ | default (print $.Release.Name "-rabbitmq") | quote }}
{{- else }}
        emptyDir: {}
{{- end }}
status: {}
{{- end }}
{{- end }}
