{{ if .Values.services.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app.service: {{ .Release.Name }}-rabbitmq
  name: {{ .Release.Name }}-rabbitmq
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    app.service: {{ .Release.Name }}-rabbitmq
status:
  loadBalancer: {}
{{ end }}
